### PR TITLE
Use alternate version

### PR DESCRIPTION
**Pull request by chuckatkins**
While you could specify an alternate version with just SRC_DIR, this does so with all the appropriate version variables getting set as well.

### CODE REVIEW

**Comment by jcfr** [comment]
A while back I started a topic to be able to support python >= `2.7.8` ... see https://github.com/jcfr/python-cmake-buildsystem/commits/support-v2.7.8

After rebasing the topic on the current master, would be great if you could test if things work as expected on your side. And eventually introduce the `parse_version_string` function to simplify the main CMakeLists.txt.

**Comment by chuckatkins** [comment]
I just tested your branch rebased on the current master and it works well for me.

**Comment by jcfr** [comment]
@chuckatkins Thanks for the feedback. This is good news. After double checking it also works on windows .. I will integrate.

**Comment by chuckatkins** [comment]
Addressed by @jcfr in a seperate branch

**Pull request closed without merging**
