### PR TITLE
Changes to allow build of 2.7.10 both shared and static on Windows

### PR DESCRIPTION
**Pull request by jrobcary**
Adding in some sources and libraries to get ssl and socketmodule to compile.

Added hashes for various versions of python.

6d9e6d913b3dfd9fdf28b54f1c7030851798b84d and 05d019dcab4f1ee501db63f4654a675df7890135
are reverses of each other and can be ignored.

Remove some unnecessary uses of the PyAPI_FUNC macro in timefuncs.h and timemodule.c, as they were wrong and causing the shared windows build to fail.

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks. I ll be travelling (vacation) this coming week. I ll work on this
after July 5th while I ll be at scipy conference.
Jc

**Comment by jcfr** [comment]
@jrobcary :+1:  Commit `adding Crypt32 library to _ssl_LIBRARIES to fix shared link.` and a fix (see 2e4cba6b6c70ae03906396adcc2e3fba5b6a3aea) inspired from your work related to `PyAPI_FUNC` issue have been integrated to master. 

Now working on integrating your other patches.

**Comment by jrobcary** [comment]
Thanks.

The _ctypes fixes from thewtex are working for me.

After rebasing against your master and doing some fixes, my pull request is not right anymore.   So I will close this and provide a new pull request.

**Comment by jcfr** [comment]
@jrobcary Thanks for working on this. Just to let you know that I am currently integrating the change related to ctypes. To avoid duplicating effort, I would suggest to work on rebasing the following commit:
* `Add in hashes for the various versions of python.`

Regarding `With the variable INSTALL_WINDOWS_TRADITIONAL to TRUE`, I think we should instead match the official layout by default.

**Comment by jrobcary** [comment]
Okay, will avoid the ctypes issue.  I will have that in one of my branches, as I need it for my
own work.

Next I will add one small change to get _socket builtin on Windows.  

Finally, with regard to INSTALL_WINDOWS_TRADITIONAL, it is by default off, giving you the behavior you want.  But for our work on Windows we count on the Windows standard layout, which works better with Windows paths.  So I hope you could reconsider.  I'll work up a changeset that you can look at.

Thx...

**Comment by jcfr** [comment]
Sorry for the confusion regarding `INSTALL_WINDOWS_TRADITIONAL`, I fully agree with you. 

Also agree with you regarding the builtin default values.

**Comment by jrobcary** [comment]
Great!

The changesets, https://github.com/davidsansome/python-cmake-buildsystem/commit/ae1648a928e9f6c1a4f49eb292c25dc49db035d7 and https://github.com/davidsansome/python-cmake-buildsystem/commit/485dd50a86db6dcb1eb60aa1d8ddd71bb71f2fd3 allow for the traditional windows installation structure.  Do you want me to create a new pull request with these included?  Or should I wait for you to accept my last pull request?

Also -- do you understand why the binascii extension uses an external zlib instead of the zlib.pyd that python builds?

**Comment by jcfr** [comment]
On Wed, Jul 15, 2015 at 7:20 PM, jrobcary <notifications@github.com> wrote:

> The changesets, ae1648a
> <https://github.com/davidsansome/python-cmake-buildsystem/commit/ae1648a928e9f6c1a4f49eb292c25dc49db035d7>
> and 485dd50
> <https://github.com/davidsansome/python-cmake-buildsystem/commit/485dd50a86db6dcb1eb60aa1d8ddd71bb71f2fd3>
> allow for the traditional windows installation structure. Do you want me to
> create a new pull request with these included? Or should I wait for you to
> accept my last pull request?
>
The changes related to the traditional layout has been integrated into
master.
See
https://github.com/davidsansome/python-cmake-buildsystem/commit/d40eb36424b264f5d97fe582479f181e00540dde


> Also -- do you understand why the binascii extension uses an external zlib
> instead of the zlib.pyd that python builds?
>
My understanding is that the zlib provided within the source of Python
can't be built using visual studio using pcbuild.sln. That is why an
external library is expected. Similarly, on unix, it the zlib source are
provided for convenience and are not considered by the top-level
"configure" script.

Thanks
Jc



-- 
+1 919 869 8849

**Pull request closed without merging**
